# Archivo environment.yml para crear entorno Anaconda

name: diabetes-prediction
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.22.3
  - pandas=1.4.2
  - scikit-learn=1.0.2
  - matplotlib=3.5.1
  - seaborn=0.11.2
  - openpyxl=3.0.9
  - joblib=1.1.0
  - jupyterlab=3.3.2
  - pip=22.0.4
  - pip:
    - imbalanced-learn==0.9.0
    - shap==0.40.0
    - yellowbrick==1.4
    - mlflow==1.25.1

# Para crear el entorno: conda env create -f environment.yml
# Para activar el entorno: conda activate diabetes-prediction